### ISSUE TITLE
how to export current diagram into a json format

### ISSUE THREAD

**Issue by seanchann** [DanielNetzer/ngx-diagrams#17]
**Is your feature request related to a problem? Please describe.**

if you need to get the relationship of the current graph, this relationship needs to do some processing in the background, it very difficult to do it.

**Describe the solution you'd like**

support api.  we can call this api export current the relationship of the graph to json format

**Comment by DanielNetzer** [comment]
@seanchann Would accept PR's for this feature if you are interested to help. otherwise it might take some time so support it.

**Comment by dylanlt** [comment]
Is there a live demo somewhere? I'd like to see how this can be used because the lack of export ability implies limited usefulness.

**Comment by DanielNetzer** [comment]
@dylanlt https://danielnetzer.github.io/ngx-diagrams/?path=/story/examples--simple fixed the storybook.
there is a playground application inside the project that you can look at.
