### ISSUE TITLE
Unable to break links when connected to input node

### ISSUE THREAD

**Issue by GlitchEclipse** [DanielNetzer/ngx-diagrams#27]
**Describe the bug**
Unable to break links when connected to input nodes.

**To Reproduce**
Implement the playgrounds example. In the ngOnInit() code there is the option to set more than one link. Change 	outPortN2.setMaximumLinks(1) to outPortN2.setMaximumLinks(100).

**Expected behavior**
Expected to be able to drag the link off the input node in the same way you can drag to start one from the output node. 

In the screenshot I cannot break the links going to the blue input nodes. Also if you look closely at the input connection circles, they don't line up. 

![image](https://user-images.githubusercontent.com/20146526/84277635-6669a680-aaf9-11ea-9362-b54ff29d9daa.png)

**Comment by DanielNetzer** [comment]
Hi @GlitchEclipse, I've started working on 2 new functionalities to address this issue.
1. Magnetic Inputs
2. Actionable Links (On-Hover should reveal action icons)
Both of those are something possible to achieve as is, but will require creating a custom link and a custom input
