### ISSUE TITLE
Question of selection of current node and diagram events

### ISSUE THREAD

**Issue by GlitchEclipse** [DanielNetzer/ngx-diagrams#29]
Couple of questions regarding diagram events and node selection. 

1. What is the quickest way for me to get the currently selected node from the diagram? I was using the   (actionStartedFiring) event to drill down into the action, but felt they might be a quicker way of doing that. Is there just a method I am call? I didn't see one in the diagram engine, but could have missed it. 

2. Is the   (actionStartedFiring) the only event that can be called for an action. I am thinking a separate action for when it is clicked would help. I was hoping to call different methods for when something is clicked versus when it is moved? For example, I want to open an info panel when I click the node to some details, versus when it is moved I don't want that to happen.

**Comment by DanielNetzer** [comment]
I feel this questions come up because the lack of documentation which is something I'll work on in the upcoming week.
There are 3 events you can subscribe to, 
```
	@Output() actionStartedFiring: EventEmitter<BaseAction> = new EventEmitter();
	@Output() actionStillFiring: EventEmitter<BaseAction> = new EventEmitter();
	@Output() actionStoppedFiring: EventEmitter<BaseAction> = new EventEmitter();
```
Which will fire all sorts of actions according to what happened, the available actions are:
InvalidLinkDestroyed, LinkCreatedAction, LooseLinkDestroyed, MoveCanvasAction, MoveItemsAction, SelectingAction (this is the one you are after), 

Example snippet how to work with fired actions:
```
onActionStarted(action: BaseAction) {
    // handle new links creation
    if (action instanceof LinkCreatedAction) {
      const targetNode = action.getInPortNode();
      const sourceNode = action.getOutPortNode();
      const srcPort = action.link.getSourcePort();
      this.nodesService.updateLinkConnection(sourceNode.id, srcPort.id, targetNode.id, this.agentId);
    } else if (action instanceof LooseLinkDestroyed || action instanceof InvalidLinkDestroyed) {
      const sourceNode = action.getOutPortNode();
      const srcPort = action.link.getSourcePort();
      this.nodesService.updateLinkConnection(sourceNode.id, srcPort.id, null, this.agentId);
    }
  }
```
